version: '3'
services:
  neo4j:
    image: neo4j:4.2.0
    hostname: barista
    container_name: neo4j-barista
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      NEO4J_AUTH: neo4j/barista
      NEO4J_dbms_memory_pagecache_size: 4G
      NEO4J_dbms.memory.heap.initial_size: 4G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\"]"